/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function initCore(): string
export declare function createLobEngine(): boolean
export declare function loadAiModel(weightsPath: string): boolean
export declare function loadAiModelFull(weightsPath: string, tkanPath: string): boolean
export declare function resetIcTracker(): boolean
export declare function getIcStatus(): string
export declare function triggerPreflightWarmup(weightsPath: string, tkanPath: string, minIc?: number | undefined | null, warmupTicks?: number | undefined | null, testingTicks?: number | undefined | null): boolean
export declare function getPreflightStatus(): string
export declare function startOmsEngine(symbol: string, initialBalance?: number | undefined | null, apiKey?: string | undefined | null, apiSecret?: string | undefined | null, isTestnet?: boolean | undefined | null): boolean
export declare function evaluateOmsTick(sabBuffer: Buffer): string
export declare function getOmsMetrics(): string
export declare function getPositionSnapshot(): string
export declare function startIngestion(sabBuffer: Buffer): boolean
export declare function getMicrostructureMetrics(): string
export declare function getDynamicCollars(entryPrice: number, positionSide: string): string
export declare function calculateCsLvrScoreNapi(symbol: string, high: number, low: number, open: number, close: number, volumeUsd5M: number, bestBid: number, bestAsk: number, priceChange5M: number, volume5M: number): number
export declare class NativeUniverseScanner {
  constructor(maxActiveAssets: number)
  updateTicker(symbol: string, high: number, low: number, open: number, close: number, volumeUsd5M: number, bestBid: number, bestAsk: number, priceChange5M: number, volume5M: number): void
  rankUniverse(): string
  getTopK(): Array<string>
}
export declare class NativeMultiStreamManager {
  constructor(maxActiveAssets: number)
  activeSymbols(): Array<string>
  stopAll(): void
}
