/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function initCore(): string
export declare function createLobEngine(): boolean
export declare function loadAiModel(weightsPath: string): boolean
export declare function loadAiModelFull(weightsPath: string, tkanPath: string): boolean
export declare function resetIcTracker(): boolean
export declare function getIcStatus(): string
export declare function triggerPreflightWarmup(weightsPath: string, tkanPath: string, minIc?: number | undefined | null, warmupTicks?: number | undefined | null, testingTicks?: number | undefined | null): boolean
export declare function getPreflightStatus(): string
export declare function startOmsEngine(symbol: string, initialBalance?: number | undefined | null, apiKey?: string | undefined | null, apiSecret?: string | undefined | null, isTestnet?: boolean | undefined | null): boolean
export declare function evaluateOmsTick(sabBuffer: Buffer): string
export declare function getOmsMetrics(): string
export declare function getPositionSnapshot(): string
export declare function startIngestion(sabBuffer: Buffer, symbols?: Array<string> | undefined | null): boolean
export declare function getMicrostructureMetrics(): string
export declare function getDynamicCollars(entryPrice: number, positionSide: string): string
export declare function calculateCsLvrScoreNapi(symbol: string, high: number, low: number, open: number, close: number, volumeUsd5M: number, bestBid: number, bestAsk: number, priceChange5M: number, volume5M: number): number
export declare function updateAssetReturnNapi(assetIdx: number, returnVal: number): boolean
export declare function getCovarianceMatrixNapi(): string
export declare function getCorrelationMatrixNapi(): string
export declare function calculateCcDfkSizeNapi(assetIdx: number, expectedReturn: number, gkVol: number, bidAskSpreadBp: number, accountBalance: number, currentPrice: number, activeWeightsJson?: string | undefined | null): string
export declare function getMultiAssetCollarsNapi(entryPrice: number, gkVol: number, isLong: boolean): string
export declare function evaluateMultiAssetSignalsNapi(sabBuffer: Buffer, activeSymbolsJson: string): string
export declare function startMultiAssetOmsNapi(initialBalanceUsd: number, symbolsJson?: string | undefined | null): boolean
export declare function submitMultiAssetIntentBytesNapi(packetBuffer: Buffer, midPrice: number, top5DepthUsd: number, stepSize: number, tickSize: number, portfolioLeverage: number, avgCorrelation: number): Buffer
export declare function submitMultiAssetIntentNapi(assetIdx: number, intentJson: string, midPrice: number, top5DepthUsd: number, stepSize: number, tickSize: number, portfolioLeverage: number, avgCorrelation: number): string
export declare function applyMultiAssetFillNapi(reportJson: string): boolean
export declare function getMultiAssetOmsMetricsNapi(assetIdx: number): string
export declare function popNextIntentPacketBytesNapi(): Buffer | null
export declare function popNextIntentPacketNapi(): string | null
export declare function syncMultiOmsSabNapi(sabBuffer: Buffer): boolean
export declare function createMultiAssetLobManagerNapi(): boolean
export declare function startPhase5OrchestratorNapi(symbols: Array<string>): boolean
export declare function stopPhase5OrchestratorNapi(): boolean
export declare function getPhase5OrchestratorMetricsNapi(): string
export declare class NativeUniverseScanner {
  constructor(maxActiveAssets: number)
  updateTicker(symbol: string, high: number, low: number, open: number, close: number, volumeUsd5M: number, bestBid: number, bestAsk: number, priceChange5M: number, volume5M: number): void
  rankUniverse(): string
  getTopK(): Array<string>
}
export declare class NativeMultiStreamManager {
  constructor(maxActiveAssets: number)
  activeSymbols(): Array<string>
  updateSubscriptions(newTopK: Array<string>): Promise<Array<string>>
  stopAll(): void
}
