export const SAB_SLOTS = {
  TIMESTAMP_NS: 0,
  OBI: 1,
  CVD: 2,
  SPREAD_VELOCITY: 3,
  BEST_BID_PRICE: 4,
  BEST_BID_QTY: 5,
  BEST_ASK_PRICE: 6,
  BEST_ASK_QTY: 7,
  LIQUIDATION_TOTAL_VOL: 8,
  LIQUIDATION_BUY_VOL: 9,
  LIQUIDATION_SELL_VOL: 10,
  
  // Top 20 Bids (11..50)
  TOP_BIDS_START: 11,
  // Top 20 Asks (51..90)
  TOP_ASKS_START: 51,

  DROPPED_EVENTS: 91,
  SEQUENCE_NUM: 92,

  // AI & Latency Metrics (93..104)
  AI_DIRECTION: 93,
  AI_CONFIDENCE: 94,
  AI_HORIZON_MS: 95,
  AI_TIMESTAMP_NS: 96,
  AI_DIRECTION_MAGNITUDE: 97,
  MEASURED_RTT_MS: 98,
  LATENCY_PENALTY_COEFF: 99,
  DYNAMIC_SLIPPAGE_TICKS: 100,
  ROLLING_IC: 101,
  IS_MODEL_DRIFTED: 102,
  AI_INFERENCE_LATENCY_NS: 103,
  AI_INFERENCE_SEQ_NUM: 104,

  // OMS Position Ledger Metrics (105..111)
  OMS_POSITION_QTY: 105,
  OMS_AVG_ENTRY_PRICE: 106,
  OMS_REALIZED_PNL: 107,
  OMS_UNREALIZED_PNL: 108,
  OMS_LEVERAGE: 109,
  OMS_CUM_VOLUME_USD: 110,
  OMS_TOTAL_TRADES: 111,

  // Micro-Burst & Dynamic Dispersion Slots (112..120)
  HAWKES_INTENSITY: 112,
  MICROBURST_SCORE: 113,
  REALIZED_VOLATILITY: 114,
  LAST_SHORT_FILL_PRICE: 115,
  LAST_LONG_FILL_PRICE: 116,
  LAST_SHORT_FILL_TIME: 117,
  LAST_LONG_FILL_TIME: 118,
  SHORT_COOLDOWN_LOCK: 119,
  LONG_COOLDOWN_LOCK: 120,
} as const;
