import * as fs from "fs";
import * as path from "path";

// Import native addon generated by napi-rs
// eslint-disable-next-line @typescript-eslint/no-var-requires
const nativeAddon = require("../../index.js");

function main(): void {
  console.log("=".repeat(75));
  console.log("BATBOT_V11 NAPI ZERO-LOCK HOT-SWAP & IC RESET ORCHESTRATOR");
  console.log("=".repeat(75));

  const projectRoot = process.cwd();
  const weightsPath = path.join(projectRoot, "models", "cfc_weights.safetensors");

  console.log(`[Hot-Swap] Validating SafeTensors file: '${weightsPath}'...`);
  if (!fs.existsSync(weightsPath)) {
    console.error(`❌ Weights file missing at '${weightsPath}'`);
    process.exit(1);
  }

  const stat = fs.statSync(weightsPath);
  if (stat.size === 0) {
    console.error(`❌ Weights file at '${weightsPath}' is empty (0 bytes)!`);
    process.exit(1);
  }

  console.log(`  [PASS] Weights file verified (${stat.size} bytes, modified: ${stat.mtime.toISOString()}).`);

  // Step 1: Query initial IC status
  if (typeof nativeAddon.getIcStatus === "function") {
    console.log(`\n[IC Status - PRE HOT-SWAP]: ${nativeAddon.getIcStatus()}`);
  }

  // Step 2: Atomic Hot-Swap via NAPI RCU Pointer Swap
  console.log("\n[Hot-Swap] Step 1/2: Triggering NAPI loadAiModel RCU pointer swap...");
  if (typeof nativeAddon.loadAiModel !== "function") {
    console.error("❌ NAPI export 'loadAiModel' is missing!");
    process.exit(1);
  }

  const loaded = nativeAddon.loadAiModel(weightsPath);
  if (!loaded) {
    console.error(`❌ NAPI loadAiModel failed to load weights from '${weightsPath}'!`);
    process.exit(1);
  }
  console.log("  [SUCCESS] NAPI zero-lock RCU hot-swap completed! Live engine now referencing updated PyTorch weights.");

  // Step 3: Reset IC Tracker window
  console.log("\n[Hot-Swap] Step 2/2: Resetting rolling Spearman IC Tracker window...");
  if (typeof nativeAddon.resetIcTracker !== "function") {
    console.error("❌ NAPI export 'resetIcTracker' is missing!");
    process.exit(1);
  }

  const resetSuccess = nativeAddon.resetIcTracker();
  console.log(`  [SUCCESS] NAPI resetIcTracker result: ${resetSuccess}`);

  // Step 4: Verify post-reset IC status
  if (typeof nativeAddon.getIcStatus === "function") {
    const postStatus = nativeAddon.getIcStatus();
    console.log(`\n[IC Status - POST HOT-SWAP]: ${postStatus}`);
    
    try {
      const parsed = JSON.parse(postStatus);
      if (parsed.is_drifted === false && parsed.ic === 0) {
        console.log("\n" + "=".repeat(75));
        console.log("[BATBOT_V11] RECALIBRATION COMPLETE: Model hot-swapped & IC tracker reset to clean state!");
        console.log("=" .repeat(75));
      }
    } catch {
      // Ignore JSON parse errors if format is plain text
    }
  }
}

main();
