import * as fs from "fs";
import * as path from "path";
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

// Import native addon functions generated by napi-rs
// eslint-disable-next-line @typescript-eslint/no-var-requires
const nativeAddon = require("../../index.js");

export interface RecalibrationStatus {
  isRecalibrating: boolean;
  driftTickCounter: number;
  lastAttemptTimestamp: number;
  lastSuccessTimestamp: number;
  totalRecalibrations: number;
  lastError: string | null;
  isShadowMode: boolean;
}

export type RecalibrationSuccessCallback = () => void;

interface ChildProcessError extends Error {
  code?: number | string;
  signal?: string;
  killed?: boolean;
  stdout?: string;
  stderr?: string;
}

export class AutoRecalibrationManager {
  private static instance: AutoRecalibrationManager | null = null;

  private isRecalibrating = false;
  private isShadowMode = false;
  private shadowTickCounter = 0;
  private driftTickCounter = 0;
  private sustainedDriftThreshold = 50; // 50 consecutive ticks below IC threshold (0.0300)
  private cooldownMs = 60000; // 60s cooldown between recalibration attempts
  private lastAttemptTimestamp = 0;
  private lastSuccessTimestamp = 0;
  private totalRecalibrations = 0;
  private lastError: string | null = null;
  private onSuccessCallback: RecalibrationSuccessCallback | null = null;

  private projectRoot: string;
  private dataDir: string;
  private signalsPath: string;
  private weightsPath: string;
  private errorLogPath: string;

  private constructor() {
    this.projectRoot = process.cwd();
    this.dataDir = path.join(this.projectRoot, "data");
    this.signalsPath = path.join(this.dataDir, "signals.jsonl");
    this.weightsPath = path.join(this.projectRoot, "models", "cfc_weights.safetensors");
    this.errorLogPath = path.join(this.dataDir, "recalibration_errors.log");
  }

  public static getInstance(): AutoRecalibrationManager {
    if (!AutoRecalibrationManager.instance) {
      AutoRecalibrationManager.instance = new AutoRecalibrationManager();
    }
    return AutoRecalibrationManager.instance;
  }

  public setOnSuccessCallback(callback: RecalibrationSuccessCallback): void {
    this.onSuccessCallback = callback;
  }

  public setSustainedDriftThreshold(ticks: number): void {
    this.sustainedDriftThreshold = ticks;
  }

  public enableShadowMode(): void {
    if (!this.isShadowMode) {
      this.isShadowMode = true;
      console.log("[BATBOT_V11][SHADOW_MODE] Shadow Training & Paper Calibration Mode ACTIVATED.");
    }
  }

  public disableShadowMode(): void {
    if (this.isShadowMode) {
      this.isShadowMode = false;
      console.log("[BATBOT_V11][SHADOW_MODE] Shadow Training Mode DEACTIVATED.");
    }
  }

  public isInShadowMode(): boolean {
    return this.isShadowMode;
  }

  public getStatus(): RecalibrationStatus {
    return {
      isRecalibrating: this.isRecalibrating,
      driftTickCounter: this.driftTickCounter,
      lastAttemptTimestamp: this.lastAttemptTimestamp,
      lastSuccessTimestamp: this.lastSuccessTimestamp,
      totalRecalibrations: this.totalRecalibrations,
      lastError: this.lastError,
      isShadowMode: this.isShadowMode,
    };
  }

  public evaluateShadowTick(seq: bigint, ic: number): void {
    if (!this.isShadowMode) return;

    this.shadowTickCounter++;
    // Periodically trigger background model retraining in Shadow Mode every 300 ticks (~3 seconds)
    if (
      this.shadowTickCounter >= 300 &&
      !this.isRecalibrating &&
      Date.now() - this.lastAttemptTimestamp >= this.cooldownMs
    ) {
      this.shadowTickCounter = 0;
      console.log("[BATBOT_V11][SHADOW_MODE] Triggering background PyTorch calibration training...");
      void this.runRecalibrationPipeline(ic);
    }
  }

  /**
   * Monitor tick metrics for model drift and programmatically trigger self-healing.
   */
  public evaluateTickDrift(ic: number, isDrifted: boolean): void {
    if (isDrifted || ic < 0.0300) {
      this.driftTickCounter++;
      if (
        this.driftTickCounter >= this.sustainedDriftThreshold &&
        !this.isRecalibrating &&
        Date.now() - this.lastAttemptTimestamp >= this.cooldownMs
      ) {
        // Trigger background auto-recalibration pipeline asynchronously
        void this.runRecalibrationPipeline(ic);
      }
    } else {
      this.driftTickCounter = 0;
    }
  }

  /**
   * Resolve the Python binary executable path, prioritizing the project's virtual environment.
   */
  private getPythonExecutable(): string {
    const venvPythonWin = path.join(this.projectRoot, "training", ".venv", "Scripts", "python.exe");
    const venvPythonPosix = path.join(this.projectRoot, "training", ".venv", "bin", "python");

    if (fs.existsSync(venvPythonWin)) {
      return venvPythonWin;
    }
    if (fs.existsSync(venvPythonPosix)) {
      return venvPythonPosix;
    }

    return process.platform === "win32" ? "python" : "python3";
  }

  /**
   * Execute autonomous training, hot-swapping, and self-healing pipeline.
   */
  public async runRecalibrationPipeline(currentIc: number): Promise<boolean> {
    if (this.isRecalibrating) {
      return false;
    }

    this.isRecalibrating = true;
    this.lastAttemptTimestamp = Date.now();
    this.lastError = null;

    console.log(
      `[BATBOT_V11][AUTO-RECALIBRATION] Triggered auto-recalibration due to sustained MODEL_DRIFT (IC: ${currentIc.toFixed(4)}, Drift Ticks: ${this.driftTickCounter}).`
    );

    try {
      // Step 1: Ensure dataset signals log exists and has data
      if (!fs.existsSync(this.signalsPath)) {
        throw new Error(`Telemetry signals file missing at '${this.signalsPath}'. Cannot extract LOB tick features.`);
      }

      const stats = fs.statSync(this.signalsPath);
      if (stats.size < 100) {
        throw new Error(`Telemetry signals file '${this.signalsPath}' contains insufficient data (${stats.size} bytes).`);
      }

      const pythonCmd = this.getPythonExecutable();
      console.log(
        `[BATBOT_V11][AUTO-RECALIBRATION] Step 1/4: Executing Python data preparation (prepare_data.py) using runtime '${pythonCmd}'...`
      );
      const prepScript = path.join(this.projectRoot, "training", "prepare_data.py");

      const prepResult = await execFileAsync(pythonCmd, [prepScript], {
        cwd: this.projectRoot,
        env: { ...process.env },
        timeout: 300000, // 5 min timeout for data preparation
      });

      if (prepResult.stderr && prepResult.stderr.trim().length > 0) {
        console.warn(`[BATBOT_V11][AUTO-RECALIBRATION] Data prep stderr log: ${prepResult.stderr.trim()}`);
      }

      console.log(`[BATBOT_V11][AUTO-RECALIBRATION] Step 2/4: Executing PyTorch CfC neural network trainer (train_cfc.py)...`);
      const trainScript = path.join(this.projectRoot, "training", "train_cfc.py");

      const trainResult = await execFileAsync(pythonCmd, [trainScript], {
        cwd: this.projectRoot,
        env: { ...process.env },
        timeout: 900000, // 15 min extended timeout for deep neural network training
      });

      if (trainResult.stderr && trainResult.stderr.trim().length > 0) {
        console.warn(`[BATBOT_V11][AUTO-RECALIBRATION] Training stderr log: ${trainResult.stderr.trim()}`);
      }

      // Step 3: Validate generated SafeTensors weights file
      if (!fs.existsSync(this.weightsPath)) {
        throw new Error(`Trained SafeTensors file not found at expected path: '${this.weightsPath}'.`);
      }

      const weightsStat = fs.statSync(this.weightsPath);
      if (weightsStat.size === 0) {
        throw new Error(`Exported SafeTensors file '${this.weightsPath}' is empty (0 bytes).`);
      }

      console.log(
        `[BATBOT_V11][AUTO-RECALIBRATION] Step 3/4: SafeTensors validation passed (${weightsStat.size} bytes). Executing zero-lock NAPI RCU Hot-Swap...`
      );

      // Step 4: Atomic Hot-Swap via NAPI RCU pointer swap in Rust
      const loaded = nativeAddon.loadAiModel ? nativeAddon.loadAiModel(this.weightsPath) : false;
      if (!loaded) {
        throw new Error(`NAPI loadAiModel failed to load weights from '${this.weightsPath}'. Engine remains uncalibrated.`);
      }

      // Step 5: Reset IC Tracker window and clear drift state
      if (typeof nativeAddon.resetIcTracker === "function") {
        nativeAddon.resetIcTracker();
      }

      this.driftTickCounter = 0;
      this.lastSuccessTimestamp = Date.now();
      this.totalRecalibrations++;
      this.isRecalibrating = false;

      console.log(
        `[BATBOT_V11][AUTO-RECALIBRATION] Step 4/4: Self-healing pipeline COMPLETED SUCCESSFULLY! Model hot-swapped & IC tracking window reset.`
      );

      if (this.onSuccessCallback) {
        this.onSuccessCallback();
      }

      return true;
    } catch (err: unknown) {
      const childErr = err as ChildProcessError;
      const baseMsg = childErr.message || String(err);
      const rawStderr = childErr.stderr ? childErr.stderr.trim() : "";
      const rawStdout = childErr.stdout ? childErr.stdout.trim() : "";
      const isKilled = childErr.killed ? `[KILLED BY NODE TIMEOUT (signal: ${childErr.signal || "SIGTERM"})]` : "";

      let errorMsg = `${baseMsg} ${isKilled}`.trim();
      if (rawStderr) {
        errorMsg += `\n--- PYTHON STDERR TRACEBACK ---\n${rawStderr}`;
      }
      if (rawStdout && !rawStderr) {
        errorMsg += `\n--- PYTHON STDOUT LOG ---\n${rawStdout}`;
      }

      this.lastError = errorMsg;
      this.isRecalibrating = false;

      const logPayload = `[${new Date().toISOString()}] [RECALIBRATION_FAILURE] ${errorMsg}\n`;
      try {
        fs.appendFileSync(this.errorLogPath, logPayload, { encoding: "utf-8" });
      } catch (logErr) {
        console.error(`Failed to write to recalibration_errors.log: ${String(logErr)}`);
      }

      console.error(
        `[BATBOT_V11][AUTO-RECALIBRATION ERROR] Pipeline execution failed! Remaining in IDLE_ACTIVE safety clamp.\nReason: ${errorMsg}`
      );

      return false;
    }
  }
}

