import * as fs from "fs";
import * as path from "path";
import { execFile, execSync } from "child_process";
import { promisify } from "util";
import * as readline from "readline";
import { CLIDashboard } from "../telemetry/dashboard";
import { TerminalOutputMux } from "../telemetry/terminalMux";

const execFileAsync = promisify(execFile);

// Import native addon functions generated by napi-rs
// eslint-disable-next-line @typescript-eslint/no-var-requires
const nativeAddon = require("../../index.js");

export interface RecalibrationStatus {
  isRecalibrating: boolean;
  driftTickCounter: number;
  lastAttemptTimestamp: number;
  lastSuccessTimestamp: number;
  totalRecalibrations: number;
  lastError: string | null;
  isShadowMode: boolean;
}

export type RecalibrationSuccessCallback = () => void;
export type RecalibrationStateChangeCallback = (state: "TRAINING_LOCK" | "RECALIBRATING" | "LIVE_ACTIVE") => void;

interface ChildProcessError extends Error {
  code?: number | string;
  signal?: string;
  killed?: boolean;
  stdout?: string;
  stderr?: string;
}

export class AutoRecalibrationManager {
  private static instance: AutoRecalibrationManager | null = null;

  private isRecalibrating = false;
  private isPromptActive = false;
  private recalibrationFailed = false;
  private isShadowMode = false;
  private shadowTickCounter = 0;
  private driftTickCounter = 0;
  private sustainedDriftThreshold = 50; // 50 consecutive ticks below IC threshold (0.0300)
  private cooldownMs = 60000; // 60s cooldown between recalibration attempts
  private lastAttemptTimestamp = 0;
  private lastSuccessTimestamp = 0;
  private totalRecalibrations = 0;
  private lastError: string | null = null;
  private onSuccessCallback: RecalibrationSuccessCallback | null = null;
  private onStateChangeCallback: RecalibrationStateChangeCallback | null = null;

  private projectRoot: string;
  private dataDir: string;
  private signalsPath: string;
  private weightsPath: string;
  private errorLogPath: string;

  private constructor() {
    this.projectRoot = process.cwd();
    this.dataDir = path.join(this.projectRoot, "data");
    this.signalsPath = path.join(this.dataDir, "signals.jsonl");
    this.weightsPath = path.join(this.projectRoot, "models", "cfc_weights.safetensors");
    this.errorLogPath = path.join(this.dataDir, "recalibration_errors.log");
  }

  public static getInstance(): AutoRecalibrationManager {
    if (!AutoRecalibrationManager.instance) {
      AutoRecalibrationManager.instance = new AutoRecalibrationManager();
    }
    return AutoRecalibrationManager.instance;
  }

  public setOnSuccessCallback(callback: RecalibrationSuccessCallback): void {
    this.onSuccessCallback = callback;
  }

  public setOnStateChangeCallback(callback: RecalibrationStateChangeCallback): void {
    this.onStateChangeCallback = callback;
  }

  public setSustainedDriftThreshold(ticks: number): void {
    this.sustainedDriftThreshold = ticks;
  }

  public enableShadowMode(): void {
    if (!this.isShadowMode) {
      this.isShadowMode = true;
      console.log("[BATBOT_V11][SHADOW_MODE] Shadow Training & Paper Calibration Mode ACTIVATED.");
    }
  }

  public disableShadowMode(): void {
    if (this.isShadowMode) {
      this.isShadowMode = false;
      console.log("[BATBOT_V11][SHADOW_MODE] Shadow Training Mode DEACTIVATED.");
    }
  }

  public isInShadowMode(): boolean {
    return this.isShadowMode;
  }

  public isPromptingUser(): boolean {
    return this.isPromptActive;
  }

  public getStatus(): RecalibrationStatus {
    return {
      isRecalibrating: this.isRecalibrating || this.isPromptActive,
      driftTickCounter: this.driftTickCounter,
      lastAttemptTimestamp: this.lastAttemptTimestamp,
      lastSuccessTimestamp: this.lastSuccessTimestamp,
      totalRecalibrations: this.totalRecalibrations,
      lastError: this.lastError,
      isShadowMode: this.isShadowMode,
    };
  }

  public evaluateShadowTick(seq: bigint, ic: number): void {
    if (!this.isShadowMode || this.isRecalibrating || this.isPromptActive) return;

    this.shadowTickCounter++;
    if (
      this.shadowTickCounter >= 300 &&
      !this.isRecalibrating &&
      !this.isPromptActive &&
      Date.now() - this.lastAttemptTimestamp >= this.cooldownMs
    ) {
      this.shadowTickCounter = 0;
      console.log("[BATBOT_V11][SHADOW_MODE] Triggering background PyTorch calibration training...");
      void this.runRecalibrationPipeline(ic);
    }
  }

  public resetStateToLive(): void {
    this.isRecalibrating = false;
    this.isPromptActive = false;
    this.recalibrationFailed = false;
    this.driftTickCounter = 0;
    if (this.onStateChangeCallback) {
      this.onStateChangeCallback("LIVE_ACTIVE");
    }
  }

  public evaluateTickDrift(ic: number, isDrifted: boolean): void {
    if (this.isRecalibrating) {
      return;
    }

    if (isDrifted) {
      this.driftTickCounter++;
      // Exponential backoff cooldown if previous recalibration failed
      const effectiveCooldown = this.recalibrationFailed
        ? Math.min(300000, this.cooldownMs * 2)
        : this.cooldownMs;

      if (
        this.driftTickCounter >= this.sustainedDriftThreshold &&
        !this.isRecalibrating &&
        Date.now() - this.lastAttemptTimestamp >= effectiveCooldown
      ) {
        void this.runRecalibrationPipeline(ic);
      }
    } else {
      this.driftTickCounter = 0;
    }
  }

  private getPythonExecutable(): string {
    const venvPythonWin = path.join(this.projectRoot, "training", ".venv", "Scripts", "python.exe");
    const venvPythonPosix = path.join(this.projectRoot, "training", ".venv", "bin", "python");

    if (fs.existsSync(venvPythonWin)) {
      return venvPythonWin;
    }
    if (fs.existsSync(venvPythonPosix)) {
      return venvPythonPosix;
    }

    return process.platform === "win32" ? "python" : "python3";
  }

  private killLocalPythonProcesses(): void {
    try {
      if (process.platform === "win32") {
        execSync("taskkill /F /IM python.exe /T", { stdio: "ignore" });
      } else {
        execSync("pkill -9 -f prepare_data.py || true", { stdio: "ignore" });
      }
      console.log("[BATBOT_V11][OVERRIDE] Active Python data preparation processes terminated.");
    } catch (_err) {
      // Ignore if no process was running
    }
  }

  private cleanupLockAndProgressFiles(): void {
    const lockFile = path.join(this.projectRoot, ".training.lock");
    const progressFile = path.join(this.projectRoot, ".training_progress");
    try {
      if (fs.existsSync(lockFile)) fs.unlinkSync(lockFile);
      if (fs.existsSync(progressFile)) fs.unlinkSync(progressFile);
      console.log("[BATBOT_V11][CLEANUP] Residual .training.lock and progress files cleared.");
    } catch (e: unknown) {
      console.warn(`[BATBOT_V11][CLEANUP] Notice during cleanup: ${String(e)}`);
    }
  }

  public async runRecalibrationPipeline(currentIc: number): Promise<boolean> {
    if (this.isRecalibrating) {
      return false;
    }

    // Set attempt timestamp IMMEDIATELY at entry to enforce cooldown on all execution paths
    this.lastAttemptTimestamp = Date.now();
    this.recalibrationFailed = false;

    // Single-Flight Atomic Mutex Acquisition (Non-blocking: Engine remains LIVE_ACTIVE)
    this.isRecalibrating = true;

    let isSuccess = false;

    try {
      console.log(
        `[BATBOT_V11][SHADOW-RECALIBRATION] Triggered background recalibration (IC: ${currentIc.toFixed(4)}, Drift Ticks: ${this.driftTickCounter}). Engine remains LIVE_ACTIVE trading on Generation N weights.`
      );

      this.cleanupLockAndProgressFiles();
      this.lastError = null;

      // Step 1: Ensure dataset signals log exists and has data
      if (!fs.existsSync(this.signalsPath)) {
        throw new Error(`Telemetry signals file missing at '${this.signalsPath}'. Cannot extract LOB tick features.`);
      }

      const stats = fs.statSync(this.signalsPath);
      if (stats.size < 100) {
        throw new Error(`Telemetry signals file '${this.signalsPath}' contains insufficient data (${stats.size} bytes).`);
      }

      const pythonCmd = this.getPythonExecutable();
      console.log(
        `[BATBOT_V11][SHADOW-RECALIBRATION] Step 1/4: Executing Python data preparation (prepare_data.py) using runtime '${pythonCmd}'...`
      );
      const prepScript = path.join(this.projectRoot, "training", "prepare_data.py");

      const prepResult = await execFileAsync(pythonCmd, [prepScript], {
        cwd: this.projectRoot,
        env: { ...process.env },
        timeout: 300000,
      });

      if (prepResult.stderr && prepResult.stderr.trim().length > 0) {
        console.warn(`[BATBOT_V11][SHADOW-RECALIBRATION] Data prep stderr log: ${prepResult.stderr.trim()}`);
      }

      // Step 2: Execute 100% Free Local Asynchronous PyTorch 2.6 Background Trainer
      console.log(`[BATBOT_V11][SHADOW-RECALIBRATION] Step 2/4: Executing 100% Free Local PyTorch 2.6 Background Recalibrator (local_async_trainer.py)...`);
      const trainerScript = path.join(this.projectRoot, "training", "local_async_trainer.py");

      const trainResult = await execFileAsync(pythonCmd, [trainerScript], {
        cwd: this.projectRoot,
        env: { ...process.env, PYTHONUNBUFFERED: "1" },
        timeout: 300000,
      });

      if (trainResult.stderr && trainResult.stderr.trim().length > 0) {
        console.warn(`[BATBOT_V11][SHADOW-RECALIBRATION] Local trainer stderr log: ${trainResult.stderr.trim()}`);
      }

      console.log(`[BATBOT_V11][SHADOW-RECALIBRATION] Local PyTorch 2.6 Background Training PASSED!`);

      // Step 3: Validate generated SafeTensors weights file & Holdout Verification
      if (!fs.existsSync(this.weightsPath)) {
        throw new Error(`Trained SafeTensors file not found at expected path: '${this.weightsPath}'.`);
      }

      const weightsStat = fs.statSync(this.weightsPath);
      if (weightsStat.size < 100) {
        throw new Error(`Exported SafeTensors file '${this.weightsPath}' is empty or invalid (${weightsStat.size} bytes).`);
      }

      console.log(
        `[BATBOT_V11][SHADOW-RECALIBRATION] Step 3/4: SafeTensors validation passed (${weightsStat.size} bytes). Executing zero-lock NAPI RCU Atomic Hot-Swap...`
      );

      // Step 4: Atomic Hot-Swap via NAPI RCU pointer swap in Rust (Zero HFT Latency Pause)
      const loaded = nativeAddon.loadAiModel ? nativeAddon.loadAiModel(this.weightsPath) : false;
      if (!loaded) {
        throw new Error(`NAPI loadAiModel failed to load weights from '${this.weightsPath}'. Engine remains uncalibrated.`);
      }

      // Step 5: Reset IC Tracker window and clear drift state
      if (typeof nativeAddon.resetIcTracker === "function") {
        nativeAddon.resetIcTracker();
      }

      this.driftTickCounter = 0;
      this.lastSuccessTimestamp = Date.now();
      this.totalRecalibrations++;
      isSuccess = true;

      console.log(
        `[BATBOT_V11][SHADOW-RECALIBRATION] Step 4/4: Self-healing pipeline COMPLETED SUCCESSFULLY! Model hot-swapped to Generation ${this.totalRecalibrations}. IC tracking window reset.`
      );

      if (this.onSuccessCallback) {
        this.onSuccessCallback();
      }

      return true;
    } catch (err: unknown) {
      const childErr = err as ChildProcessError;
      const baseMsg = childErr.message || String(err);
      const rawStderr = childErr.stderr ? childErr.stderr.trim() : "";
      const rawStdout = childErr.stdout ? childErr.stdout.trim() : "";
      const isKilled = childErr.killed ? `[KILLED BY NODE TIMEOUT (signal: ${childErr.signal || "SIGTERM"})]` : "";

      let errorMsg = `${baseMsg} ${isKilled}`.trim();
      if (rawStderr) {
        errorMsg += `\n--- PYTHON STDERR TRACEBACK ---\n${rawStderr}`;
      }
      if (rawStdout && !rawStderr) {
        errorMsg += `\n--- PYTHON STDOUT LOG ---\n${rawStdout}`;
      }

      this.lastError = errorMsg;
      this.recalibrationFailed = true;

      const logPayload = `[${new Date().toISOString()}] [RECALIBRATION_FAILURE] ${errorMsg}\n`;
      try {
        fs.appendFileSync(this.errorLogPath, logPayload, { encoding: "utf-8" });
      } catch (logErr) {
        console.error(`Failed to write to recalibration_errors.log: ${String(logErr)}`);
      }

      console.warn(
        `\x1b[33m[BATBOT_V11][SHADOW-RECALIBRATION NOTICE] Background recalibration attempt failed. Trading continues seamlessly on Generation N model weights.\nReason: ${errorMsg}\x1b[0m`
      );

      return false;
    } finally {
      this.isRecalibrating = false;
      // Do NOT set state to TRAINING_LOCK. Engine continues trading on last known good weights.
    }
  }
}
